//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.18 at 11:42:33 AM MEZ 
//


package at.ac.ait.formatRegistry;

import javax.xml.bind.annotation.XmlRegistry;

import uk.gov.nationalarchives.pronom.PRONOMReport;

/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the uk.gov.nationalarchives.pronom package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: uk.gov.nationalarchives.pronom
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PRONOMReport.ReportFormatDetail.FileFormat.ExternalSignature }
     * 
     */
    public PRONOMReport.ReportFormatDetail.FileFormat.ExternalSignature createPRONOMReportReportFormatDetailFileFormatExternalSignature() {
        return new PRONOMReport.ReportFormatDetail.FileFormat.ExternalSignature();
    }

    /**
     * Create an instance of {@link PRONOMReport.ReportFormatDetail.FileFormat.Document.Author }
     * 
     */
    public PRONOMReport.ReportFormatDetail.FileFormat.Document.Author createPRONOMReportReportFormatDetailFileFormatDocumentAuthor() {
        return new PRONOMReport.ReportFormatDetail.FileFormat.Document.Author();
    }

    /**
     * Create an instance of {@link PRONOMReport.ReportFormatDetail.FileFormat.Document.Publisher }
     * 
     */
    public PRONOMReport.ReportFormatDetail.FileFormat.Document.Publisher createPRONOMReportReportFormatDetailFileFormatDocumentPublisher() {
        return new PRONOMReport.ReportFormatDetail.FileFormat.Document.Publisher();
    }

    /**
     * Create an instance of {@link PRONOMReport.ReportFormatDetail.FileFormat.CompressionType }
     * 
     */
    public PRONOMReport.ReportFormatDetail.FileFormat.CompressionType createPRONOMReportReportFormatDetailFileFormatCompressionType() {
        return new PRONOMReport.ReportFormatDetail.FileFormat.CompressionType();
    }

    /**
     * Create an instance of {@link PRONOMReport }
     * 
     */
    public PRONOMReport createPRONOMReport() {
        return new PRONOMReport();
    }

    /**
     * Create an instance of {@link PRONOMReport.ReportFormatDetail.FileFormat.CompressionType.CompressionIdentifier }
     * 
     */
    public PRONOMReport.ReportFormatDetail.FileFormat.CompressionType.CompressionIdentifier createPRONOMReportReportFormatDetailFileFormatCompressionTypeCompressionIdentifier() {
        return new PRONOMReport.ReportFormatDetail.FileFormat.CompressionType.CompressionIdentifier();
    }

    /**
     * Create an instance of {@link PRONOMReport.ReportFormatDetail.FileFormat.FileFormatIdentifier }
     * 
     */
    public PRONOMReport.ReportFormatDetail.FileFormat.FileFormatIdentifier createPRONOMReportReportFormatDetailFileFormatFileFormatIdentifier() {
        return new PRONOMReport.ReportFormatDetail.FileFormat.FileFormatIdentifier();
    }

    /**
     * Create an instance of {@link PRONOMReport.ReportFormatDetail.FileFormat.InternalSignature.ByteSequence }
     * 
     */
    public PRONOMReport.ReportFormatDetail.FileFormat.InternalSignature.ByteSequence createPRONOMReportReportFormatDetailFileFormatInternalSignatureByteSequence() {
        return new PRONOMReport.ReportFormatDetail.FileFormat.InternalSignature.ByteSequence();
    }

    /**
     * Create an instance of {@link PRONOMReport.ReportFormatDetail.FileFormat.InternalSignature }
     * 
     */
    public PRONOMReport.ReportFormatDetail.FileFormat.InternalSignature createPRONOMReportReportFormatDetailFileFormatInternalSignature() {
        return new PRONOMReport.ReportFormatDetail.FileFormat.InternalSignature();
    }

    /**
     * Create an instance of {@link PRONOMReport.ReportFormatDetail }
     * 
     */
    public PRONOMReport.ReportFormatDetail createPRONOMReportReportFormatDetail() {
        return new PRONOMReport.ReportFormatDetail();
    }

    /**
     * Create an instance of {@link PRONOMReport.ReportFormatDetail.FileFormat.Document }
     * 
     */
    public PRONOMReport.ReportFormatDetail.FileFormat.Document createPRONOMReportReportFormatDetailFileFormatDocument() {
        return new PRONOMReport.ReportFormatDetail.FileFormat.Document();
    }

    /**
     * Create an instance of {@link PRONOMReport.ReportFormatDetail.FileFormat.RelatedFormat }
     * 
     */
    public PRONOMReport.ReportFormatDetail.FileFormat.RelatedFormat createPRONOMReportReportFormatDetailFileFormatRelatedFormat() {
        return new PRONOMReport.ReportFormatDetail.FileFormat.RelatedFormat();
    }

    /**
     * Create an instance of {@link PRONOMReport.ReportFormatDetail.FileFormat.Document.DocumentIdentifier }
     * 
     */
    public PRONOMReport.ReportFormatDetail.FileFormat.Document.DocumentIdentifier createPRONOMReportReportFormatDetailFileFormatDocumentDocumentIdentifier() {
        return new PRONOMReport.ReportFormatDetail.FileFormat.Document.DocumentIdentifier();
    }

    /**
     * Create an instance of {@link PRONOMReport.ReportFormatDetail.FileFormat }
     * 
     */
    public PRONOMReport.ReportFormatDetail.FileFormat createPRONOMReportReportFormatDetailFileFormat() {
        return new PRONOMReport.ReportFormatDetail.FileFormat();
    }

}
