//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.18 at 11:42:33 AM MEZ 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://pronom.nationalarchives.gov.uk", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package uk.gov.nationalarchives.pronom;
